class ApiKey {
  static String stripeSecretKey = "sk_test_51NfwjOBVWwMJFEhrRjnwXiLfqWOEbNhwtPifL3cSYpXW4R6OQN1jEgi1xS7Vsgv8D8WevYeR4PrcwvhvQWC8TYZM003XX2FJYO";
  static String stripePublishableKey = "pk_test_51NfwjOBVWwMJFEhrBZ1wH9txGoYhATAv3YUzI9GoVsmrhUXcVCJkxt0zLz7Q6wtyWl2TV9j2kgTqerV4HGSvkXdG00QwLTFyYx";
}