// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXwuEomtCS4JLwz-BLikeeL8d6fV6078w',
    appId: '1:759159093073:android:37ab69484a8cd73399c570',
    messagingSenderId: '759159093073',
    projectId: 'enrollment-8bef4',
    databaseURL: 'https://enrollment-8bef4-default-rtdb.firebaseio.com',
    storageBucket: 'enrollment-8bef4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnA4Qb0WChH0nvDm7j2-osYRcMWBXtgVQ',
    appId: '1:759159093073:ios:9e0ea2b4694bd53c99c570',
    messagingSenderId: '759159093073',
    projectId: 'enrollment-8bef4',
    databaseURL: 'https://enrollment-8bef4-default-rtdb.firebaseio.com',
    storageBucket: 'enrollment-8bef4.appspot.com',
    iosClientId: '759159093073-a1pd159se651eu550v7tuut5smqus71i.apps.googleusercontent.com',
    iosBundleId: 'com.example.schoolManagement',
  );
}
